### ISSUE TITLE
How to run this script?

### ISSUE THREAD

**Issue by emoju** [h5bp-bot/scripts#5]
This throws me errors, what was going on?

```
node update_site_branch.sh
```

Might be a bug in master so a patch release HIGHLY welcomed.

**Comment by d10** [comment]
@emoju You’re supposed to run it using `bash`. See here for an example: https://github.com/h5bp/html5boilerplate.com/blob/master/.travis.yml#L6-11.

**Comment by emoju** [comment]
No bash doesn't work too plz document this better

I cant reopen the issue so 'll create new one. thanks for all the help

@alrra dont close issues way to fast :-1:
